spring.application.name=inka_backend

# H2 Local Database (file-based, persists between restarts)
spring.datasource.url=jdbc:h2:file:./data/inkadb;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# SQL init — seed data on every startup (safe with create-drop)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# H2 Console (for debugging at http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Google OAuth2 Credentials
spring.security.oauth2.client.registration.google.client-id=613582869489-objfmprle76fqq9tubbdjvmamrudv6d2.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# The URL where Google sends the user back to your Spring Boot app
# This must match what you put in the Google Cloud Console!
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google


#Cludinary credentials
cloudinary.cloud-name=djbzlugf0
cloudinary.api-key=535511179928287
cloudinary.api-secret=etXNEw15xfNMmNm3vkrIpnCKZZY