spring.application.name=inka_backend
# MySQL Connection Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/inka_clothing_store?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Aka-vdsinka2810

# Hibernate & SQL Initialization
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.show-sql=true